language: csharp
solution: TP2_laba_8.sln
install:
- sudo apt-get install g++ cmake
- nuget restore 'TP2_laba_8.sln'
- nuget install NUnit.Runners -Version 3.7.0 -OutputDirectory testrunner
script:
- xbuild /p:Configuration=Release TP2_laba_8.sln
- mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./CalcuTests1/bin/Release/CalcuTests1.dll
